### ISSUE TITLE
Support package-local nicknames in CLISP

### ISSUE THREAD

**Issue by phoe** [roswell/clisp_head#1]
It's getting hard to keep on working with CLISP, since more and more CL code depends on package-local nicknames, and keeping that software working on CLISP requires keeping and downloading a separate PLN-less branch for it.

https://gitlab.com/gnu-clisp/clisp/-/merge_requests/3 has not been merged in over a year for reasons I don't know. Please cherry-pick these commits on top of the current master branch to support package-local nicknames on CLISP.

**Comment by snmsts** [comment]
I'm neutral to the idea PLN itself. It would be nice to have pln and I feel nothing morally wrong with distributing patched version here. but applying patch would make it a bit trouble some to maintain here as well.
If you don't mind, I'd give you access for [this](https://github.com/roswell/clisp_head) and [related repo](https://github.com/roswell/clisp_bin) so that you can make it by yourself and change roswell's clisp default (with option?).
and hoping you can take care some related issues if I don't have vacant time.

**Comment by phoe** [comment]
Sure, I can do this.

I want to make a local fork of CLISP on GitHub and build `clisp_head` from that. CLISP is not a fast-moving repository and I can try to keep it in sync with the main repository.

If this sounds good, would you mind creating a `roswell/clisp` repository and giving me owner access there, so I can fork CLISP there and apply PLN patches to it?

**Comment by snmsts** [comment]
Idea itself would be ok. And I'd like to share current status.
roswell/clisp exist already and it is already [referred](https://github.com/roswell/clisp_bin/blob/5d52a8a26400c9d0ddc42e54b3620e1dc90cfee4/Makefile#L5) to build clisp_head.
currently roswell/clisp is sync by ci daily via [this script](https://github.com/roswell/daily_maintenance/blob/master/clisp/Lakefile)
so I was thinking give you access for
roswell/clisp_bin
roswell/clisp_head
roswell/clisp
roswell/daily_maintenance

I thought just write access for all of these would be ok.

to hear your plan... 
- stop daily_maintenance script. (I guess you don't need access for roswell/daily_maintenance if it is properly stopped)
- admin access to roswell/clisp? (I guess you'd like to sync it manually?)
- write access for roswell/clisp_head (You should have)

Are those what you want?

**Comment by phoe** [comment]
* I think you only need to exclude the CLISP repos if the script does anything more.
* I'll need admin access to the clisp repository - I'll want to update it manually. (I don't expect the repository to move fast, so manual updates should be OK.)
* I'll need the necessary accesses to be able to make new releases for clisp_head. Are these done automatically via CI in some way every time clisp_head gets new commits?

**Comment by phoe** [comment]
OK, I have admin access in clisp now. What is the architecture of making clisp builds in Roswell?

**Comment by snmsts** [comment]
Not yet automatically done.

currently need manually upload hash file on release via

```
ros install snmsts/sn.github roswell/sbcl_bin
curl -L -O https://raw.githubusercontent.com/roswell/clisp_bin/main/Makefile
GH_REPO=clisp_head GITHUB_OAUTH_TOKEN=xxxx make upload-hash
```

If I'm not wrong. :(

so my task lists.
- [x] give admin access for roswell/clisp.
- [x] while waiting for modification on roswell/clisp. I stop autoupdate script.
- [x] after roswell/clisp changed. I'll update ci for making tag and tsv.
- [x] give write access for roswell/clisp_head 
- [x] give better instruction for update.

**Comment by phoe** [comment]
OK - please let me know when it's safe to merge PLN patches into the clisp repo, then we can proceed.

**Comment by snmsts** [comment]
https://github.com/roswell/daily_maintenance/commit/187c4c3489bb66304dbda5541c0a476be18d704b safe now.
you can start modify roswell/clisp freely.

**Comment by phoe** [comment]
Patches from https://gitlab.com/gnu-clisp/clisp/-/merge_requests/3 are now applied to the repository.

We can try building CLISP!

**Comment by snmsts** [comment]
confirmed. wait for a while...

**Comment by snmsts** [comment]
running tag action now... hope it will release and upload hash file for it.

**Comment by snmsts** [comment]
running linux/osx action now. it will upload built archives.

**Comment by phoe** [comment]
OK, sounds good. Is there a Windows build job as well?

**Comment by snmsts** [comment]
I can't make it.
could you build recent clisp on windows?

**Comment by phoe** [comment]
Nope, I have no Windows machine.

Is there some kind of Travis or other CI job that can build it for us and push the files under some tag? Alternatively, does CLISP build under Wine?

Alternatively, is it possible to create a Windows GitHub action to build it?

**Comment by snmsts** [comment]
No idea. I should say, Are there someone build recent clisp on windows?
on cygwin 3years ago is the newest I know. https://cygwin.com/packages/summary/clisp.html

**Comment by snmsts** [comment]
```
$ ros -L clisp-head run -- --version
GNU CLISP 22.1.29 (2022-01-29) (built on 7b18d243be6e [172.17.0.2])
Software: GNU C 4.8.4
cc -std=gnu99 -W -Wswitch -Wcomment -Wpointer-arith -Wreturn-type -Wmissing-declarations -Wimplicit -Wno-sign-compare -Wno-format-nonliteral -O -fwrapv -fno-strict-aliasing -DNO_ASM -DENABLE_UNICODE -DNO_TERMCAP_NCURSES -DDYNAMIC_FFI -DDYNAMIC_MODULES  libgnu.a  -ldl /tmp/clisp/../ffcall/lib/libffcall.a  /tmp/clisp/../sigsegv/lib/libsigsegv.a
SAFETY=0 HEAPCODES ONE_FREE_BIT_HEAPCODES WIDE_HARD SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.12
libffcall 2.4
Features: (REGEXP WILDCARD SYSCALLS I18N LOOP COMPILER CLOS MOP CLISP ANSI-CL COMMON-LISP LISP=CL INTERPRETER LOGICAL-PATHNAMES SOCKETS GENERIC-STREAMS FFI GETTEXT UNICODE BASE-CHAR=CHARACTER WORD-SIZE=64 PC386 UNIX)
C Modules: (clisp i18n syscalls regexp)
Installation directory: /home/snmsts/.roswell/impls/x86-64/linux/clisp-head/22.1.29/lib/clisp-22.1.29/
User language: ENGLISH
Machine: X86_64 (X86_64) DESKTOP-5BEO7QB.localdomain [127.0.1.1]
```

works fine so far...

**Comment by phoe** [comment]
I can confirm, I installed `clisp-head` and I'm playing around with it right now.

Also, I have no idea about Windows CLISP builds.

**Comment by phoe** [comment]
OK, I guess we are almost done. There is one fix that's required in the PLN implementation of CLISP, but that will be added soon.

How is it possible to trigger a build of clisp_head? Is there some GitHub action that should be run manually?

**Comment by snmsts** [comment]
Good to know it functions. I made an issue for windows for the future task.
What you need to do when you update roswell/clisp is all via github action. 

Expected order is
1. **tag** which prepare release to upload archives.
2. **osx** / **linux** which upload archives for each architecture.
3. **tsv** which update https://github.com/roswell/clisp_head/releases/download/files/clisp_head.tsv

I think wrong order wouldn't destroy any data.
Repeat all the actions until it get finished if you confused. or ask me.

**Comment by phoe** [comment]
Good! Thank you.

Is it OK to add this list order to this repository's README file so it's obvious how to build it in case I forget or somebody else needs to do it in the future?

**Comment by snmsts** [comment]
Thank you. Of course! my no documentation tendency is coming just from my laziness...

**Comment by phoe** [comment]
OK - I've updated the README. Thanks!
