### ISSUE TITLE
Multiple releases from the same commit

### ISSUE THREAD

**Issue by phoe** [roswell/clisp_head#4]
The GitHub action created releases [22.12.19](https://github.com/roswell/clisp_head/releases/tag/22.12.19) to [22.12.22](https://github.com/roswell/clisp_head/releases/tag/22.12.22) from the same commit without any changes made to the repository. These releases seem effectively the same. Why?

**Comment by snmsts** [comment]
sorry.... upload hash file on release which showing until which commit it builds and failure for upload hash cause failure when to make new tag. sorry for ignorance for 2month...

**Comment by phoe** [comment]
![Zrzut ekranu z 2023-03-15 08-06-45](https://user-images.githubusercontent.com/15045546/225232564-983f8335-618d-447f-a7e5-fb805e2d8da4.png)

Still ongoing since 6th Match.

**Comment by snmsts** [comment]
solved
